services:
  db:
    image: postgres:16
    container_name: lovelace_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: lovelace
      POSTGRES_USER: lovelace
      POSTGRES_PASSWORD: lovelace
    ports:
      - "5432:5432"
    volumes:
      - lovelace_db_data:/var/lib/postgresql/data
      - ./scripts/db:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U lovelace -d lovelace" ]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build: ./backend
    container_name: lovelace_back
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      # Sobrescribimos el host para que use el nombre del servicio 'db'
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: lovelace_front
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  lovelace_db_data: